version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./cloud-grafana/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./cloud-grafana/shared:/shared
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./cloud-grafana/grafana-data:/var/lib/grafana
      - ./cloud-grafana/shared:/shared
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
